"""empty message

Revision ID: 395df0a2f9f6
Revises: 62beb4175403
Create Date: 2017-10-23 15:32:03.875202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395df0a2f9f6'
down_revision = '62beb4175403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('master_password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'master_password_hash')
    # ### end Alembic commands ###
